name: Rust Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        # wait for the database to be ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # we need to install the sqlx-cli to run the migrations
      - name: Install sqlx-cli
        run: cargo install sqlx-cli

      - name: Run database migrations
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        run: sqlx migrate run

      - name: Prepare sqlx
        run: cargo sqlx prepare --check

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        run: cargo test
